[terminal]
vt = 1

[default_session]
# command = "agreety --cmd /bin/sh"
command = "tuigreet --cmd niri"
# command = "Hyprland -c /etc/greetd/hyprland.conf"

user = "greeter"

# [initial_session]
# command = "/sbin/Hyprland"
# user = "nova"
